### ISSUE TITLE
Classic?

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#159]
Is this CascLib able to open Classic? I know your current CascView can't (it says it can't find the specified file), but I'm unsure if that's because of CascLib or just the app.

Thanks :)

**Comment by WainPetopia** [comment]
Ok, at least it's not just me. Thanks for checking. I hope it's not hard to fix :)

**Comment by ladislav-zezula** [comment]
I was investigating the problem and it seems that the ROOT file was not in the ENCODING manifest at all. This is bad, because, I need the encoding key to load it. No idea why is this happening (hell, the game must load it from somewhere), but it is not the first time.

Last time it happened to me, it was pre-release incomplete installation of wow-classic. I solved it by a completely fresh installation.

**Comment by ladislav-zezula** [comment]
This is the schema of the latest build (31830):
* .build info -> build key: a46865b6b382b963ffe78b3d77f7cfcb
* build key -> encoding: 73822cbc6e4751d39ab1c9e287c20b3a 28803da571d758c082776070d0aae847 
* build key -> root: eb5d4606422623fa0e69bf22c241dd69 (not found in ENCODING)

Now I know that there is ROOT file, whose CKey is eb5d4606422623fa0e69bf22c241dd69, but I don't know its EKey, thus cannot locate it in IDX files or in data files. I wonder how the game does it.

**Comment by WainPetopia** [comment]
I'll ask around :)

**Comment by WainPetopia** [comment]
I spoke to Martin Benjamins, who said that it's definiely in encoding: :
"There's only 2 ways I know of for finding ekey and that's either through parsing encoding or if it is already mentioned in build config (which it isn't)"

**Comment by ladislav-zezula** [comment]
Fixed in commit https://github.com/ladislav-zezula/CascLib/commit/9b87ccabd3201d97edbd07fcfb890858d8207734.
Also, CascView rebuilt and uploaded.

**Comment by WainPetopia** [comment]
Thanks for the quick fix! :)

**Comment by WainPetopia** [comment]
I grabbed CascView but it's still not showing file names for Classic. Unless I'm doing something wrong...
![cascviewclassic](https://user-images.githubusercontent.com/25504585/64921418-6fe20e80-d806-11e9-883f-01ec4b0878a6.PNG)

**Comment by ladislav-zezula** [comment]
Sometimes, for an unknown reason, it takes quite a while till the file gets propagated through. Please, check the version of CascView.

![Untitled](https://user-images.githubusercontent.com/3244359/64925477-52ef1080-d7f1-11e9-9a79-ef14234e79d1.png)

**Comment by WainPetopia** [comment]
Hmm, I have the right version of CascView. I wonder why mine isn't working. Should I need a listfile, or does Classic still have its own? Whether or not I provide a listfile (in csv format) it doesn't use file names. I ran Classic just to be sure it was updated properly, and I ensured everything was closed before I ran it.

**Comment by ladislav-zezula** [comment]
If CascView recognizes a ROOT that needs listfile, it asks for it. It also recognizes which one (either pre-8.2 text file or post-8.2 CSV listfile). Your symptoms indicate that the bug still exists. I'll look at it.

**Comment by ladislav-zezula** [comment]
@WainPetopia , could you please download the latest commit, build a DEBUG version and try if you get an assert in `InsertEKeyEntry`?

**Comment by WainPetopia** [comment]
build a debug version in WMV? I'm happy to do it but how do I configure it to be a debug version?

**Comment by ladislav-zezula** [comment]
Debug version of CascLib.

**Comment by ladislav-zezula** [comment]
Actually, stop it. First, could you try this build?
http://www.zezula.net/cascview_wain.zip

**Comment by WainPetopia** [comment]
No luck with that. It gave me the same results, with or without listfile.csv

**Comment by ladislav-zezula** [comment]
I deployed new build of CascView (version 2.2.0.175). Fixed some loading error, which might be causing this. Please, try that out. If it still doesn't work, we will have to try some loggins on your side. In that case, please, let me know off-github (zezula at-volny dot cz)

**Comment by WainPetopia** [comment]
Well, that's embarrassing. It works, but the reason it failed before is I was using the wrong listfile format. I was providing it with a csv when it needs an old-style .txt file with no file id column or it fails to work. I had (wrongly) assumed that Classic used the same storage as BfA and needed file IDs now. I'm so sorry to mislead you with that. Though since the csv format is now standard it might be nice if the app could detect if the user provided a csv and be able to use it (just ignore the file id column), but no biggie. :)

**Comment by ladislav-zezula** [comment]
Yeah, surprisingly Classic doesn't use the CSV.

I'll help you that this won't happen again for you:

1) Put all listfiles into a folder. Mine is `C:\Tools32\ListFiles`
2) Set that folder as "Listfile Folder" in CascView (and MPQEditor as well, if you still happen to use it)
3) Make sure that the TXT listfile is named `World of Warcraft*.txt`
4) Make sure that the CSV listfile is named `World of Warcraft*.csv`

Now if you open a storage, CascView will ask you to enter a listfile. However, the correct one is already pre-filled in.

**Comment by ladislav-zezula** [comment]
Also, maybe it's time to re-think the listfile strategy. WoW remains the only game that actually does need listfile, so I might as well change the settings to:
* Text Listfile (for World of Warcraft pre-8.2 and Classic)
* CSV Listfile (for World of Warcraft 8.2 or newer)
